basic:
    name: 'test 1'
    environments:
        production: 'https://www.medical.nestlebabyandme.pl'
        staging: 'https://152104-dig0033913-nutrition-babyme-poland.pantheonsite.io'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - '/user/register?destination='
        - /user/login
        - /wszystkie-produkty
        - /wszystkie-produkty/product-stage/3
        - /wszystkie-produkty/product-brand/6
        - /wszystkie-produkty/product-brand/13
        - /wszystkie-produkty/product-stage/1
        - /wszystkie-produkty/product-stage/11
        - /all-articles
        - /materialy-wideo
        - /nan-optipro-plus
        - /prenan
        - /nan-expertpro
        - /nestle-sinlac
        - /nan-supremepro-1
        - /wczesniaki-0
        - /niemowleta
        - /dzieci-po-1-roku-zycia
        - /nan
        - /nancare
        - /diagnostyka-alergii-pokarmowej
        - /nawilza-chlodzi-wyleczy-czerwone-oko
        - /objawy-alergii-u-dzieci
        - /mikrobiota-sojusznik-czy-wrog
        - /polityka-nestle-dotyczaca-cookies
        - /regulamin-serwisu
        - /nestle-babyme-medical-lietuva
        - /faq
        - /redakcja-nestle-babyme-medical
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
